import type { DefaultTheme } from 'vitepress';

export const sidebar: DefaultTheme.Sidebar = [
	{
		text: 'Введение',
		collapsed: false,
		items: [
			{ text: 'Что это?', link: '/guide/introduction/what-is-it' },
			{ text: 'Начало работы', link: '/guide/introduction/getting-started' },
			{ text: 'Доступные команды', link: '/guide/introduction/commands' },
		],
	},
	{
		text: 'Основы',
		collapsed: false,
		items: [
			{ text: 'Страницы', link: '/guide/essentials/pages' },
			{ text: 'UI-кит', link: '/guide/essentials/ui' },
			{ text: 'Шрифты', link: '/guide/essentials/fonts' },
			{ text: 'Иконки', link: '/guide/essentials/icons' },
			{ text: 'Выгрузка верстки', link: '/guide/essentials/deploy-layout' },
			{ text: 'Работа с API', link: '/guide/essentials/api' },
			{ text: 'Captcha', link: '/guide/essentials/captcha' },
			{ text: 'Использование viewport в компонентах', link: '/guide/essentials/viewport-in-components' },
			{ text: 'Работа с модалкми', link: '/guide/essentials/modals' },
		],
	},
	{
		text: 'Pug-миксины',
		collapsed: true,
		items: [
			{ text: 'base-accordion', link: '/guide/pug-mixins/base-accordion' },
			{ text: 'icon', link: '/guide/pug-mixins/icon' },
			{ text: 'image', link: '/guide/pug-mixins/image' },
			{ text: 'social-share', link: '/guide/pug-mixins/social-share' },
			{ text: 'tooltip', link: '/guide/pug-mixins/tooltip' },
		],
	},
	{
		text: 'Sass-миксины',
		collapsed: true,
		items: [
			{ text: 'icon', link: '/guide/sass-mixins/icon' },
			{ text: 'fluid', link: '/guide/sass-mixins/fluid' },
		],
	},
	{
		text: 'Vue-компоненты',
		collapsed: true,
		items: [
			{
				text: 'Инпуты',
				items: [
					{ text: 'XInputCheckbox', link: '/guide/components/inputs/XInputCheckbox' },
					{ text: 'XInputCode', link: '/guide/components/inputs/XInputCode' },
					{ text: 'XInputDate', link: '/guide/components/inputs/XInputDate' },
					{ text: 'XInputField', link: '/guide/components/inputs/XInputField' },
					{ text: 'XInputFile', link: '/guide/components/inputs/XInputFile' },
					{ text: 'XInputPassword', link: '/guide/components/inputs/XInputPassword' },
					{ text: 'XInputRadio', link: '/guide/components/inputs/XInputRadio' },
					{ text: 'XInputRange', link: '/guide/components/inputs/XInputRange' },
					{ text: 'XInputSearch', link: '/guide/components/inputs/XInputSearch' },
					{ text: 'XInputSelect', link: '/guide/components/inputs/XInputSelect' },
					{ text: 'XInputSwitch', link: '/guide/components/inputs/XInputSwitch' },
					{ text: 'XInputText', link: '/guide/components/inputs/XInputText' },
					{ text: 'XInputTextarea', link: '/guide/components/inputs/XInputTextarea' },
				],
			},
			{
				text: 'Модалки',
				items: [
					{ text: 'XModal', link: '/guide/components/modals/XModal' },
				],
			},
			{
				text: 'Слайдеры',
				items: [
					{ text: 'XSlider', link: '/guide/components/sliders/XSlider' },
					{ text: 'XSliderGallery', link: '/guide/components/sliders/XSliderGallery' },
					{ text: 'XSliderHero', link: '/guide/components/sliders/XSliderHero' },
				],
			},
			{
				text: 'UI',
				items: [
					{ text: 'XAccordion', link: '/guide/components/ui/XAccordion' },
					{ text: 'XDropdown', link: '/guide/components/ui/XDropdown' },
					{ text: 'XIcon', link: '/guide/components/ui/XIcon' },
					{ text: 'XImage', link: '/guide/components/ui/XImage' },
					{ text: 'XShowMore', link: '/guide/components/ui/XShowMore' },
					{ text: 'XSkeleton', link: '/guide/components/ui/XSkeleton' },
					{ text: 'XTabs', link: '/guide/components/ui/XTabs' },
				],
			},
		],
	},
	{
		text: 'Composables',
		collapsed: true,
		items: [
			{ text: 'useI18n', link: '/guide/composables/useI18n' },
			{ text: 'useFileInput', link: '/guide/composables/useFileInput' },
			{ text: 'useMedia', link: '/guide/composables/useMedia' },
			{ text: 'useTimer', link: '/guide/composables/useTimer' },
		],
	},
	{
		text: 'Scripts',
		collapsed: true,
		items: [
			{ text: 'calcProperties', link: '/guide/scripts/calcProperties' },
			{ text: 'mediaAutoWrapper', link: '/guide/scripts/mediaAutoWrapper' },
			{ text: 'scrollToHash', link: '/guide/scripts/scrollToHash' },
		],
	},
	{
		text: 'Директивы',
		collapsed: true,
		items: [
			{ text: 'v-observe', link: '/guide/directives/observe' },
		],
	},
	{
		text: 'Файловая структура',
		collapsed: true,
		items: [
			{ text: '📁 .github', link: '/guide/structure/github' },
			{ text: '📁 .idea', link: '/guide/structure/idea' },
			{ text: '📁 .vscode', link: '/guide/structure/vscode' },
			{ text: '📁 config', link: '/guide/structure/config' },
			{ text: '📁 dist', link: '/guide/structure/dist' },
			{ text: '📁 docs', link: '/guide/structure/docs' },
			{
				text: '📁 src',
				collapsed: true,
				link: '/guide/structure/src',
				items: [
					{ text: '📁 app', link: '/guide/structure/app' },
					{ text: '📁 assets', link: '/guide/structure/assets' },
					{ text: '📁 public', link: '/guide/structure/public' },
					{ text: '📁 styles', link: '/guide/structure/styles' },
					{ text: '📁 templates', link: '/guide/structure/templates' },
					{ text: '📁 views', link: '/guide/structure/views' },
					{ text: '📄 index.html', link: '/guide/structure/index-html' },
				],
			},
			{ text: '📄 .editorconfig', link: '/guide/structure/editorconfig' },
			{ text: '📄 .env', link: '/guide/structure/env' },
			{ text: '📄 .gitignore', link: '/guide/structure/gitignore' },
			{ text: '📄 .npmrc', link: '/guide/structure/npmrc' },
			{ text: '📄 .nvmrc', link: '/guide/structure/nvmrc' },
			{ text: '📄 env.d.ts', link: '/guide/structure/env-d-ts' },
			{ text: '📄 eslint.config.ts', link: '/guide/structure/eslint-config-js' },
			{ text: '📄 package.json', link: '/guide/structure/package-json' },
			{ text: '📄 package-lock.json', link: '/guide/structure/package-lock-json' },
			{ text: '📄 project.config.ts', link: '/guide/structure/project-config-ts' },
			{ text: '📄 README.md', link: '/guide/structure/readme-md' },
			{ text: '📄 renovate.json', link: '/guide/structure/renovate-json' },
			{ text: '📄 stylelint.config.js', link: '/guide/structure/stylelint-config-js' },
			{ text: '📄 svgo.config.js', link: '/guide/structure/svgo-config-js' },
			{ text: '📄 tsconfig.json', link: '/guide/structure/tsconfig-json' },
			{ text: '📄 tsconfig.node.json', link: '/guide/structure/tsconfig-node-json' },
			{ text: '📄 vite.config.ts', link: '/guide/structure/vite-config-ts' },
		],
	},
];
